apiVersion: v2
name: student-api
version: 0.1.16 # x-release-please-version
description: A Helm chart for deploying the Student API on EKS
appVersion: "0.1.16" # x-release-please-version
dependencies:
  - name: application
    version: 1.0.20
    repository: oci://308488080037.dkr.ecr.us-east-1.amazonaws.com
