---
application:
  config:
    clusterType: in-cluster
    applicationName: student-api
    name: svc-workshop-i
    domainName: service
    subDomainName: student
    applicationId: student-api
    team: DevOps
    repoURL: https://github.com/unixbps/student-app
  deployment:
    imagePullSecrets: ecr-pull-secret
    image:
      baseUrl: 308488080037.dkr.ecr.us-east-1.amazonaws.com
      name: student-api
      registryName: student-api
  ingressPublic:
    enabled: true
    hosts:
      - host: ""
        paths:
          - path: /student-api
            pathType: Prefix