apiVersion: v2
name: student-api
version: 0.1.3	# x-release-please-version
description: A Helm chart for deploying the Student API on EKS
appVersion: "0.1.3"	# x-release-please-version
dependencies:
	- name: application
		version: 1.0.15
	  repository: oci://252689085451.dkr.ecr.eu-west-1.amazonaws.com/application
