---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svc-student-api-dev-euw1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    team: DevOps
    environment: dev
    cluster: in-cluster
    region: eu-west-1
    domain: service
    subdomain: student
spec:
  destination:
    name: in-cluster
    namespace: service-workshop-control-student-api
  project: service-student-api
  source:
    path: ./helm/app
    repoURL: https://github.com/keyloop-platform/service_workshop-control_servicehub-360-bff
    targetRevision: main
    helm:
      releaseName: svc-student-api-dev-euw1
      valueFiles:
        - values.yaml
        - dev/values.eu-west-1.dev.yaml